exclude: 'dev-requirements.txt'

ci:
  autofix_commit_msg: |
    style: auto fixes from pre-commit hooks
  autoupdate_commit_msg: |
    ci(pre-commit): autoupdate hook versions

repos:
  - repo: local
    hooks:
      - id: autotyping
        name: Add repetitive type hints to the codebase.
        entry: python -m scripts.autotyping
        types_or: [ python, pyi ]
        language: python
        files: zcached/
        additional_dependencies:
          - autotyping==24.3.0
          - black==23.12.1
          - libcst==1.2.0

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        name: Running black in all files.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        name: Running ruff in all files.

  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.19.0
    hooks:
      - id: slotscheck
        name: Running slotscheck in all files.
        exclude: "^(?!zcached/)"
        additional_dependencies: [typing_extensions]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
        name: Check if python files are valid syntax for the ast parser
      - id: check-case-conflict
        name: Check for case conflict on file names for case insensitive systems.
      - id: check-merge-conflict
        name: Check for merge conflict syntax.
      - id: end-of-file-fixer
        name: Check for only one newline character at EOL.
      - id: trailing-whitespace
        name: Check for trailing whitespace.
        args: [--markdown-linebreak-ext=md]
