exclude: 'dev-requirements.txt'

ci:
  autofix_commit_msg: |
    style: auto fixes from pre-commit hooks
  autoupdate_commit_msg: |
    ci(pre-commit): autoupdate

repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: Running black in all files.

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        name: Running ruff in all files.

  - repo: https://github.com/ariebovenberg/slotscheck
    rev: v0.19.0
    hooks:
      - id: slotscheck
        name: Running slotscheck in all files.
        exclude: "^(?!zcached/)"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
        name: Check if python files are valid syntax for the ast parser
      - id: check-case-conflict
        name: Check for case conflict on file names for case insensitive systems.
      - id: check-merge-conflict
        name: Check for merge conflict syntax.
      - id: end-of-file-fixer
        name: Check for only one newline character at EOL.
      - id: trailing-whitespace
        name: Check for trailing whitespace.
        args: [--markdown-linebreak-ext=md]
