name: Pyright

on: [push]


jobs:
  pyright:
    runs-on: ubuntu-latest
    name: Pyright
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt -r dev-requirements.txt

      - name: Set up pyright
        run: echo "PYRIGHT_VERSION=$(python -c 'import pyright; print(pyright.__pyright_version__)')" >> $GITHUB_ENV

      - name: Run pyright (Linux)
        run: |
          python pyright .
        with:
          python-version: ${{ matrix.python-version }}
          python-platform: Linux
          warnings: true

      - name: Run pyright (Windows)
        run: |
          python pyright .
        with:
          python-platform: Windows
          no-comments: true
          warnings: true
