name: Pyright

on: [push]


jobs:
  pyright:
    name: pyright
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt -r dev-requirements.txt

      - name: Run pyright (Linux)
        run: |
          python pyright .
        with:
          python-platform: Linux
          warnings: true

      - name: Run pyright (Windows)
        run: |
          python pyright .
        with:
          python-platform: Windows
          no-comments: true
          warnings: true
