name: Pytest

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pyright pytest pytest-cov

      - name: Run pytest
        run: |
          coverage run -m pytest -v -s
